version: '3'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Evice@Pass"
    ports:
      - "1433:1433"